# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPIGGQHkW8xBDFqY2k3V5-0RXnwLHc69
"""

!pip install streamlit

# app.py

import streamlit as st
from card_optimizer import recommend_cards

st.set_page_config(page_title="Credit Card Optimizer", layout="centered")
st.title("💳 Credit Card Optimizer Agent")
st.markdown("Get the best credit card based on your monthly spending!")

st.markdown("### 📊 Enter your estimated monthly spending:")
categories = [
    "Food & Dining", "Travel", "Shopping",
    "Entertainment", "Groceries", "Fuel", "Utility Bills"
]

spend_dict = {}
for cat in categories:
    spend_dict[cat] = st.number_input(f"{cat} (in ₹)", min_value=0, value=0)

if st.button("🚀 Recommend Best Cards"):
    recommendations = recommend_cards(spend_dict)

    st.subheader("🧠 AI Recommendations")
    for rec in recommendations:
        st.markdown(f"""
        **{rec['card']}**
        - 🪙 Estimated Annual Rewards: ₹{rec['rewards']}
        - 💸 Annual Fee: ₹{rec['annual_fee']}
        - ✅ Net Savings: ₹{rec['net_savings']}
        """)

pip install streamlit -q
pip install pyngrok -q

# Replace YOUR_AUTHTOKEN with the token you copied
ngrok config add-authtoken 30KmYldCPK7PtSrfuexzK64yG42_3AvatCyUYmF6UnRgFepwb

from pyngrok import ngrok
import os

# Save your app.py in the current directory
os.system("streamlit run app.py &")
public_url = ngrok.connect(8501)
print(public_url)