# -*- coding: utf-8 -*-
"""card_optimizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFol_ZlazpHs4ZDAtFZdvTR6KPa5bmqH
"""

# card_optimizer.py

from credit_card_data import credit_cards

def recommend_cards(spend_dict):
    recommendations = []

    for card in credit_cards:
        total_rewards = 0
        for category, amount in spend_dict.items():
            reward_rate = card["category_rewards"].get(category, 0)
            total_rewards += reward_rate * amount
        net_savings = total_rewards - card["annual_fee"]
        recommendations.append({
            "card": card["name"],
            "rewards": round(total_rewards, 2),
            "net_savings": round(net_savings, 2),
            "annual_fee": card["annual_fee"]
        })

    sorted_recommendations = sorted(recommendations, key=lambda x: x["net_savings"], reverse=True)
    return sorted_recommendations[:3]  # Return top 3