# -*- coding: utf-8 -*-
"""credit_card_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZEaUespO8NmkenlvKT8vpszDyiRvWWH
"""

# credit_card_data.py

credit_cards = [
    {
        "name": "HDFC Millennia",
        "category_rewards": {
            "Shopping": 0.05,
            "Food & Dining": 0.02,
            "Travel": 0.01,
        },
        "annual_fee": 1000
    },
    {
        "name": "SBI SimplyCLICK",
        "category_rewards": {
            "Shopping": 0.10,
            "Entertainment": 0.02,
        },
        "annual_fee": 499
    },
    {
        "name": "ICICI Amazon Pay",
        "category_rewards": {
            "Shopping": 0.05,
            "Groceries": 0.02,
        },
        "annual_fee": 0
    },
    {
        "name": "Axis Magnus",
        "category_rewards": {
            "Travel": 0.1,
            "Food & Dining": 0.03,
            "Shopping": 0.02,
        },
        "annual_fee": 10000
    },
]